<?php

declare(strict_types=1);

use App\Modules\AI\Exceptions\InvalidAiResponseException;
use App\Modules\AI\Providers\MockProvider;
use App\Modules\AI\Services\AiResponseValidator;
use App\Modules\AI\ValueObjects\AiRequest;

/**
 * AiBenchmarkSuite — T-M8-028.
 *
 * Runs the in-process MockProvider against a 50-case
 * fixture and asserts that:
 *
 *   1. Every valid case produces an AiResponse that
 *      passes AiResponseValidator (i.e. the wire format
 *      we hand to the orchestrator conforms to docs/10
 *      §14).
 *   2. The provider's primary label matches the
 *      predicted_type for every case (so routing
 *      decisions in M7 stay consistent).
 *   3. Every negative case in the fixture fails the
 *      validator with a named reason — that proves the
 *      validator is actually checking the contract
 *      rather than rubber-stamping everything.
 *
 * The fixture lives at
 *   tests/fixtures/ai/benchmark_50.json
 * and is generated by /tmp/build_bench.php. See docs/15
 * §14 for the benchmark contract.
 */
beforeEach(function (): void {
    $fixturePath = __DIR__.'/../../fixtures/ai/benchmark_50.json';
    $this->fixture = json_decode((string) file_get_contents($fixturePath), true, flags: JSON_THROW_ON_ERROR);
    $this->validator = new AiResponseValidator;
});

it('loads 50 valid benchmark cases from the fixture', function (): void {
    expect($this->fixture['_meta']['valid_count'])->toBe(50)
        ->and($this->fixture['_meta']['negative_count'])->toBe(5)
        ->and(count($this->fixture['responses']))->toBe(50)
        ->and(count($this->fixture['negative_responses']))->toBe(5);
});

it('MockProvider returns a valid AiResponse for every benchmark case', function (): void {
    $provider = new MockProvider(responses: $this->fixture['responses']);

    foreach (array_keys($this->fixture['responses']) as $key) {
        $request = new AiRequest(promptName: $key, text: 'benchmark');
        $response = $provider->classify($request);

        $this->validator->validate($response);
        expect($response->predictedType)->not->toBe('')
            ->and($response->primaryLabel())->not->toBeNull();
    }
});

it('MockProvider primary label matches predicted_type for every benchmark case', function (): void {
    $provider = new MockProvider(responses: $this->fixture['responses']);

    foreach ($this->fixture['responses'] as $key => $row) {
        $request = new AiRequest(promptName: $key, text: 'benchmark');
        $response = $provider->classify($request);
        $this->validator->validate($response);

        expect($response->primaryLabel())->toBe($row['predicted_type']);
    }
});

it('every benchmark case has a confidence in the [0,1] range', function (): void {
    $provider = new MockProvider(responses: $this->fixture['responses']);

    foreach (array_keys($this->fixture['responses']) as $key) {
        $request = new AiRequest(promptName: $key, text: 'benchmark');
        $response = $provider->classify($request);
        $this->validator->validate($response);

        expect($response->confidence)->toBeGreaterThanOrEqual(0.0)
            ->and($response->confidence)->toBeLessThanOrEqual(1.0);
    }
});

it('every benchmark case has severity in the allowed enum', function (): void {
    $provider = new MockProvider(responses: $this->fixture['responses']);

    foreach (array_keys($this->fixture['responses']) as $key) {
        $request = new AiRequest(promptName: $key, text: 'benchmark');
        $response = $provider->classify($request);
        $this->validator->validate($response);

        expect(in_array($response->severity, AiResponseValidator::ALLOWED_SEVERITIES, true))->toBeTrue();
    }
});

it('every benchmark case has 0..100 quality/duplicate/fraud scores', function (): void {
    $provider = new MockProvider(responses: $this->fixture['responses']);

    foreach (array_keys($this->fixture['responses']) as $key) {
        $request = new AiRequest(promptName: $key, text: 'benchmark');
        $response = $provider->classify($request);
        $this->validator->validate($response);

        expect($response->qualityScore)->toBeGreaterThanOrEqual(0)
            ->and($response->qualityScore)->toBeLessThanOrEqual(100)
            ->and($response->duplicateScore)->toBeGreaterThanOrEqual(0)
            ->and($response->duplicateScore)->toBeLessThanOrEqual(100)
            ->and($response->fraudScore)->toBeGreaterThanOrEqual(0)
            ->and($response->fraudScore)->toBeLessThanOrEqual(100);
    }
});

it('validates all 50 cases in a single sweep', function (): void {
    $provider = new MockProvider(responses: $this->fixture['responses']);
    $failures = [];

    foreach (array_keys($this->fixture['responses']) as $key) {
        try {
            $response = $provider->classify(new AiRequest(promptName: $key, text: 'benchmark'));
            $this->validator->validate($response);
        } catch (InvalidAiResponseException $e) {
            $failures[] = "{$key}: ".$e->getMessage();
        }
    }

    expect($failures)->toBe([]);
});

it('rejects every negative case with a named failure reason', function (): void {
    $provider = new MockProvider(responses: $this->fixture['negative_responses']);
    $expected = [
        'neg_empty_labels' => 'labels_empty',
        'neg_no_primary' => 'primary_count_wrong',
        'neg_two_primary' => 'primary_count_wrong',
        'neg_bad_severity' => 'severity_invalid',
        'neg_oor_quality' => 'qualityScore_out_of_range',
    ];

    foreach ($expected as $key => $reason) {
        $request = new AiRequest(promptName: $key, text: 'benchmark');
        $response = $provider->classify($request);

        try {
            $this->validator->validate($response);
            $this->fail("expected negative case {$key} to fail validation, but it passed");
        } catch (InvalidAiResponseException $e) {
            expect($e->context['reason'] ?? null)->toBe($reason);
        }
    }
});

it('exposes a stable severity enum of {low, medium, high, critical}', function (): void {
    expect(AiResponseValidator::ALLOWED_SEVERITIES)
        ->toBe(['low', 'medium', 'high', 'critical']);
});
